namespace ReportGenerator.Report;

public sealed class ReportWriter
{
    private const string Separator = "=============================================";

    /// <summary>
    /// Writes the formatted report to stdout and to a .txt file.
    /// Returns the path of the saved file.
    /// </summary>
    public async Task<string> WriteAsync(
        string reportText,
        string outputDirectory,
        string? studentName = null,
        CancellationToken cancellationToken = default)
    {
        var formatted = Format(reportText, studentName);

        // Console output
        Console.WriteLine();
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine(formatted);
        Console.ResetColor();

        // File output
        Directory.CreateDirectory(outputDirectory);
        var timestamp = DateTimeOffset.Now.ToString("yyyyMMdd_HHmmss");
        var safeName = string.IsNullOrWhiteSpace(studentName)
            ? "report"
            : SanitizeFileName(studentName);
        var fileName = $"{safeName}_{timestamp}.txt";
        var filePath = Path.Combine(outputDirectory, fileName);

        await File.WriteAllTextAsync(filePath, formatted, cancellationToken);

        return filePath;
    }

    /// <summary>
    /// Writes to a user-specified file path instead of an auto-named file.
    /// </summary>
    public async Task<string> WriteToPathAsync(
        string reportText,
        string filePath,
        string? studentName = null,
        CancellationToken cancellationToken = default)
    {
        var formatted = Format(reportText, studentName);

        Console.WriteLine();
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine(formatted);
        Console.ResetColor();

        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrWhiteSpace(dir))
            Directory.CreateDirectory(dir);

        await File.WriteAllTextAsync(filePath, formatted, cancellationToken);
        return filePath;
    }

    private static string Format(string reportText, string? studentName)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine(Separator);
        sb.AppendLine(" TEACHER ASSESSMENT REPORT");

        if (!string.IsNullOrWhiteSpace(studentName))
            sb.AppendLine($" Student : {studentName}");

        sb.AppendLine($" Date    : {DateTimeOffset.Now:yyyy-MM-dd}");
        sb.AppendLine(Separator);
        sb.AppendLine();
        sb.AppendLine(reportText.Trim());
        sb.AppendLine();
        sb.AppendLine(Separator);
        sb.AppendLine(" Generated by ReportGenerator v1.0");
        sb.AppendLine(Separator);

        return sb.ToString();
    }

    private static string SanitizeFileName(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return string.Concat(name.Select(c => invalid.Contains(c) ? '_' : c))
                     .Replace(' ', '_')
                     .ToLowerInvariant();
    }
}
