using ReportGenerator.Report;

namespace ReportGenerator.Tests;

public sealed class ReportWriterTests
{
    private readonly ReportWriter _writer = new();

    [Fact]
    public async Task WriteAsync_CreatesFile_WithExpectedContent()
    {
        var dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(dir);

        try
        {
            var savedPath = await _writer.WriteAsync(
                reportText: "Student performed well.",
                outputDirectory: dir,
                studentName: "Bob Jones");

            Assert.True(File.Exists(savedPath));
            var content = await File.ReadAllTextAsync(savedPath);

            Assert.Contains("TEACHER ASSESSMENT REPORT", content);
            Assert.Contains("Bob Jones", content);
            Assert.Contains("Student performed well.", content);
            Assert.Contains("Generated by ReportGenerator", content);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteAsync_FileNameContainsStudentName()
    {
        var dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(dir);

        try
        {
            var savedPath = await _writer.WriteAsync(
                reportText: "Good effort.",
                outputDirectory: dir,
                studentName: "Jane Doe");

            var fileName = Path.GetFileName(savedPath);
            Assert.Contains("jane_doe", fileName);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteAsync_UsesDefaultPrefix_WhenNoStudentName()
    {
        var dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(dir);

        try
        {
            var savedPath = await _writer.WriteAsync(
                reportText: "Good effort.",
                outputDirectory: dir);

            var fileName = Path.GetFileName(savedPath);
            Assert.StartsWith("report_", fileName);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public async Task WriteToPathAsync_WritesToSpecifiedPath()
    {
        var path = Path.Combine(Path.GetTempPath(), $"{Path.GetRandomFileName()}.txt");

        try
        {
            var savedPath = await _writer.WriteToPathAsync(
                reportText: "Excellent work.",
                filePath: path,
                studentName: "Test Student");

            Assert.Equal(path, savedPath);
            Assert.True(File.Exists(path));
        }
        finally
        {
            if (File.Exists(path)) File.Delete(path);
        }
    }

    [Fact]
    public async Task WriteAsync_IncludesDate_InOutput()
    {
        var dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(dir);

        try
        {
            var savedPath = await _writer.WriteAsync("Report body.", dir);
            var content = await File.ReadAllTextAsync(savedPath);
            var expectedDate = DateTimeOffset.Now.ToString("yyyy-MM-dd");
            Assert.Contains(expectedDate, content);
        }
        finally
        {
            Directory.Delete(dir, recursive: true);
        }
    }
}
